### ISSUE TITLE
[🐞]: Breaking Wild Flax doesn't drop seeds [FABRIC BETA]

### ISSUE THREAD

**Issue by guytoothpick** [MehVahdJukaar/Supplementaries#1219]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

1.21.1-3.0.15

### Moonlight Lib Version

1.21.1-2.17.1

### Issue Detail

Breaking Wild Flax in Survival drops the item itself instead of the flax seeds.

**Comment by Xelbayria** [comment]
Try with **Moonlight lib** v2.17.2

**Comment by guytoothpick** [comment]
That version is not available on Fabric, at least on my end

**Comment by Xelbayria** [comment]
are you sure? I just checked on Curseforge and it's there. for FABRIC.

**Comment by guytoothpick** [comment]
OH MY GOODNESS
I am so sorry about that, It's not on Modrinth and I forgot about curseforge
and it still doesn't drop the seeds, just the item.
and I noticed that via the Mod Menu Mod, Supplementaries is still shown as 3.0.14
I have redownloaded it from both modrinth and Curseforge and it still registers as this.
I have no clue if that is an actual problem or if it's nothing
Sorry again!

**Comment by Xelbayria** [comment]
no worries.

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by DocAtbash** [comment]
Sorry to say, this bug is not fixed. I have reproduced this bug in both latest versions of moonlight and supplementaries (as of today) and the recommended versions on the comments of this bug report. I've also experienced the same problem with urns. Naturally generated urns drop their block variant instead of any loot.
