### ISSUE TITLE
[🗃]: Material Storage Block Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [MehVahdJukaar/Supplementaries#1273]
Add the following item and block tags to these storage blocks for unification purposes:

Flint Block: `c:storage_blocks/flint`
Feather Block: `c:storage_blocks/feather`
Soap Block: `c:storage_blocks/soap`

**Comment by MehVahdJukaar** [comment]
done, will be in next update

**Comment by TheBedrockMaster** [comment]
@MehVahdJukaar on 1.21.1 NeoForge, the Flint Block is still missing the `c:storage_blocks/flint` item tag.
