### ISSUE TITLE
[1.18-Forge] Game doesn't attempt to boot at all. (Selene Lib problem?)

### ISSUE THREAD

**Issue by Gbergz** [MehVahdJukaar/Supplementaries#149]
## Versions
- **Supplementaries**: 1.0.0 | https://www.curseforge.com/minecraft/mc-mods/supplementaries/files/3553062
- **Selene Lib**: 1.10.1 | https://www.curseforge.com/minecraft/mc-mods/selene/files/3553028
- **Forge** 38.0.14
- **Optifine Installed**: No

## Expected Behavior
That the game loads up like normal.

## Actual Behavior
Game fails to load, doesn't even pop up with a crash-report. Just stops.

## Logs
debug.log: https://gist.github.com/Gbergz/f1d540b6bcc8f1eb89e77d296647160f
latest.log: https://gist.github.com/Gbergz/a6292670e2d53588293153d29074760b

## Steps to Reproduce the Problem
1. Install Supplementaries + Selene Lib
2. Attempt to load client.
3. Wait.
4. Game stops, crashes.
5. Profit.

## Other info
I tried to just boot the game with Selene Lib, same issue. Maybe it lies there.

**-** Gbergz

**Comment by MehVahdJukaar** [comment]
Should be fixed now

**Comment by Gbergz** [comment]
Seems to load further now. However still crashes on something quark plugin.
Log: https://gist.github.com/Gbergz/dc7aedf7ddac96b2d7b671a2d8636bc0

**Comment by MehVahdJukaar** [comment]
Yeah I messed up some stuff. Disable my config button in the configs for now

**Comment by MehVahdJukaar** [comment]
should work now
