### ISSUE TITLE
[🐞]: Book piles have missing texture upon rejoining world

### ISSUE THREAD

**Issue by NoShenGG** [MehVahdJukaar/Supplementaries#1522]
### Before Continuing:

- [x] Check you are using the latest version of the mods and its dependencies
- [x] Always include a latest.log if you are crashing
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

supplementaries-1.21-3.1.8

### Moonlight Lib Version

moonlight-1.21-2.18.13-fabric

### Describe Issue

Although a similar issue has been reported prior, the conditions do not line up with the previous report. On a minimal set of mods installed, book piles that have been placed appear fine. Upon rejoining the world, the each book turns into a missing texture block. May be related to missing book type warning in log file. Attempting to use F3+T does not fix or affect the issue.

Log: [latest.log](https://github.com/user-attachments/files/20494084/latest.log)

**Comment by MehVahdJukaar** [comment]
i cant replicate. tested on 1.21 fabric with just the mod on

**Comment by NoShenGG** [comment]
That's odd. I hope it's not anything specific to my hardware configuration. Out of curiosity, which Fabric loader version and Fabric API version did you use to try to recreate it?

**Comment by NoShenGG** [comment]
My wording might have been incorrect. I don't know about /reload, but it happens when I save and quit the world in singleplayer and reopen thr world.

**Comment by MehVahdJukaar** [comment]
that was a question

**Comment by NoShenGG** [comment]
oh, sorry. I tried using /reload and it didn't affect any textures. Instead, I couldn't place down books at all until I rejoin the world. This is in singleplayer not on a server.

log: [latest.log](https://github.com/user-attachments/files/20495491/latest.log)

**Comment by NoShenGG** [comment]
It seems like it is Fabric specific. Tried replicating in NeoForge and couldn't recreate the issue.

**Comment by NoShenGG** [comment]
In my own testing, looks like a race condition between ClientReceivers.handleSyncBookTypes() setting up the itemToBooks map and PlaceableBookManagerClient.getValidModelsForBookItem() looking up the BookType in the map.

TLDR; I think sometimes it tries to read from the itemToBooks map before it is set in that instance for the client. Not sure why that's Fabric-specific or why it happens, but it did.

**Comment by oneVR** [comment]
I'm also running into this on a NeoForge 1.21.1 server. Rejoining works to fix it, and it only happens randomly to different people. I'm not sure what logs I should provide here or if they would be helpful.

![Image](https://github.com/user-attachments/assets/b5a99c77-d16c-4aef-a444-e532e67fcfd8)

**Comment by MehVahdJukaar** [comment]
fixed properly in new version

**Comment by AndiBanandi** [comment]
I'm having this issue in the pack Liminal Industries, on Forge. Big issue there, as the nether is filled with these things. Supplementaries and Moonlight Lib both up-to-date, still happening.

**Comment by slitherdisaster** [comment]
> I'm having this issue in the pack Liminal Industries, on Forge. Big issue there, as the nether is filled with these things. Supplementaries and Moonlight Lib both up-to-date, still happening.

Sorry for necroing this forum, but I'm having the same issue! Anyone know why?

**Comment by MehVahdJukaar** [comment]
Can you replicate without other mods? Place books. Then rejoin
