### ISSUE TITLE
[1.18.1] Crash on startup with Decorative Blocks

### ISSUE THREAD

**Issue by alexnmt** [MehVahdJukaar/Supplementaries#175]
Getting a crash with the new version of Decorative Blocks (1.18) on startup. 

[crash-2022-01-02_09.42.27-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/7798862/crash-2022-01-02_09.42.27-fml.txt)

**Comment by MehVahdJukaar** [comment]
I'm aware of thatm mod just updated and I need to update my compat stuff I have for it. Not at home run so patch will be out next days

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by Gbergz** [comment]
Still getting crash with Decorative Blocks + Decorative Winter.
Using Supplementaries: 1.1.5 | https://www.curseforge.com/minecraft/mc-mods/supplementaries/files/3593038

Crash-Report: https://gist.github.com/Gbergz/0d136397b045aaaae9219e2e73478a65

**Comment by Gbergz** [comment]
Ignore this, for some reason curseforge is stupid and installed 1.1.4 again when clicking update.
That launcher sometimes I swear..
