### ISSUE TITLE
Using placeable rods turn non-lava fluids into water

### ISSUE THREAD

**Issue by davidjjung** [MehVahdJukaar/Supplementaries#715]
Admittedly, this bug is on what I assume is an unsupported version--I'm currently on Supplementaries 1.18.2-1.5.18.

Using placeable, waterloggable items (such as blaze rods, sticks, and prismarine rods from Upgrade Aquatic) on non-water, non-lava fluids turns them into water. This applies everything that I can find, with no exception so far. I've tried it with fluids from Create Central Kitchen, Create, and the Undergarden--more specifically, it immediately converts the block space that was occupied by fluid into a waterlogged version of the rod item placed down. Given that it turns lava into nothing (just replacing the fluid with the block entirely), I assume that this would be best for the other fluids as well. Hopefully this is already fixed on up to date versions. Thanks for your time :)

**Comment by MehVahdJukaar** [comment]
Are those fluids tagged as water? They must be..

**Comment by davidjjung** [comment]
Ah, that might be the case given that the bubbles particles that appear when entities enter the fluid are water bubbles (blue and everything). Does that mean the issue should be fixed on their ends? It's probably worth noting that other blocks, like slabs or stairs or bars, don't turn waterlogged when placed in these fluids. Just the rods

**Comment by MehVahdJukaar** [comment]
I think I fixed this in layer version still people shouldn't tag stuff that's not water as water

**Comment by Xelbayria** [comment]
@davidjjung 
is the issue resolved or still persists? If resolved, then please close this issue, thanks!

**Comment by meeprdib** [comment]
Mod versions on 1.19.2 and below are not supported
